# foundry.toml
[profile.default]
ffi = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]

# Sepolia testnet configuration
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# Test configuration
[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Coverage
[profile.coverage]
verbosity = 3
no_match_test = "testFail"

# CI profile
[profile.ci]
fuzz = { runs = 10000 }
verbosity = 4

# Local testing
[profile.local]
verbosity = 2
gas_reports = ["PlatformToken"]
